<a href="https://colab.research.google.com/github/Chanda92/CE888/blob/master/lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# Create a (4 x 2) integer array and print it's attributes
# 2nd method
y=np.arange(8)
y.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [0]:
# Create an array of dimension (1,10) and sort it in ascending and descending order¶
# Sort Arrays and reshape 
z= [10,5,1,3,8,9,4,2,7,6]
a=np.sort(z)
a.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [0]:
# Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]
b=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(b,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# Stack two arrays of any size horizontally an vertically
# Stack two arrays of any size horizontally
a= np.array([[1,2],[3,4]])
b=np.array([[5,6,7],[8,9,10]])
np.hstack((a,b))

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [0]:
# Stack two arrays of any size Vertically 
x= np.array([[1,2,3]])
y=np.array([[5, 6, 7],[8,9,10]])
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [0]:
# Create two array of same size and find commom elements
c = np.array([[1,2,3],[2,5,3]])
d = np.array([[2,3,5],[4,1,2]])
np.intersect1d(c,d)

array([1, 2, 3, 5])

In [0]:
# Create a 2D array of 5 by 5 and find the min and max values from each row and each column
# Min Values of 2D Array
e = np.arange(2,27)
np.min(e)

2

In [0]:
# Max Values of 2D Array
np.max(e)

26

In [0]:
# Create an array of size 100 and compute the mean, median, standard deviation.
# Compute mean
f = np.arange(100)
np.mean(f)

49.5

In [0]:
# Compute median 
np.median(f)

49.5

In [0]:
# Creating Standard Deviation
np.std(f)

28.86607004772212

In [0]:
# Normalize a 5x5 random matrix
g = np.arange(4,29)
g.reshape(5,5)

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28]])

In [0]:
gmin= np.min(g)
gmax= np.max(g)

In [0]:
norm = (g - gmin) / (gmax - gmin)
norm

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [0]:
# Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?
var1 = np.random.randint(0, 10, size=(4,4,3))
var1


array([[[9, 1, 7],
        [4, 1, 3],
        [9, 5, 1],
        [8, 8, 2]],

       [[0, 9, 8],
        [9, 2, 4],
        [0, 6, 5],
        [8, 0, 3]],

       [[3, 3, 0],
        [1, 3, 2],
        [3, 8, 8],
        [4, 2, 8]],

       [[0, 2, 2],
        [6, 2, 5],
        [5, 4, 2],
        [6, 9, 1]]])

In [0]:
var2 = np.random.randint(1,5,size=(4,4))
var2

array([[2, 1, 2, 4],
       [4, 2, 1, 1],
       [3, 1, 1, 2],
       [3, 1, 3, 2]])

In [0]:
var3 = ( var2.transpose() * var1.transpose() ).transpose()
var3

array([[[18,  2, 14],
        [ 4,  1,  3],
        [18, 10,  2],
        [32, 32,  8]],

       [[ 0, 36, 32],
        [18,  4,  8],
        [ 0,  6,  5],
        [ 8,  0,  3]],

       [[ 9,  9,  0],
        [ 1,  3,  2],
        [ 3,  8,  8],
        [ 8,  4, 16]],

       [[ 0,  6,  6],
        [ 6,  2,  5],
        [15, 12,  6],
        [12, 18,  2]]])