<a href="https://colab.research.google.com/github/Chanda92/CE888/blob/master/Lab5/Recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [4]:
# import data
df= pd.read_csv("https://raw.githubusercontent.com/Chanda92/CE888/master/jester-data-1.csv")
df


74  -7.82   8.79  -9.66  -8.16  ...  99.22  -5.63  99.23  99.24  99.25
0      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
1       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
2       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
4      100  -6.17  -3.54   0.44  -8.50  ...  -3.35   0.05  -9.08  -5.05  -3.45
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24978   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24979   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24980   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 101 columns]

In [5]:
data = df.values
print(data.shape)

(24982, 101)


In [6]:
rated = np.where(data!=99)
rated[0].shape

(1835282,)

In [0]:
# helper_function ( validation set)
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(data!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(data, 0.1)

In [13]:
data[idx[0][0], idx[1][0]]

-5.78

In [14]:
# label 10% of the dataset cells as 99. 
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
#Task 2 latent factor modeling
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [0]:
# Load Data for User-ratings
data1 = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/user_ratings.csv")

In [0]:
n_latent_factors = 2

user_ratings = data1.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [21]:
latent_item_features


array([[0.953, 0.441],
       [0.147, 0.767],
       [0.899, 0.557],
       [0.652, 0.209],
       [0.95 , 0.622]])

In [22]:
latent_user_preferences

array([[0.368, 0.471],
       [0.066, 0.975],
       [0.509, 0.098],
       [0.389, 0.161],
       [0.534, 0.141],
       [0.423, 0.634],
       [0.994, 0.117],
       [0.431, 0.459],
       [0.234, 0.866],
       [0.028, 0.878]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    
def sgd(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print(mse)

In [30]:
sgd()  # Note how the MSE decreases with the number of iterations

1.3105971009927924
1.310597874079905
1.3105986447474511


In [31]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.73 ,  1.311,  4.651,  4.298,  5.162],
       [ 3.167,  1.876,  3.25 ,  7.498,  6.368],
       [ 9.   ,  1.907,  5.797,  6.635,  7.218],
       [11.02 ,  2.332,  7.095,  8.107,  8.826],
       [15.903,  1.391,  8.256,  3.244,  6.468],
       [ 2.221,  3.515,  4.488, 14.682, 11.452],
       [ 4.721,  1.166,  3.207,  4.19 ,  4.312],
       [ 6.174,  2.   ,  4.672,  7.516,  7.149],
       [ 2.549,  1.471,  2.577,  5.869,  5.002],
       [ 4.814,  0.912,  2.992,  3.086,  3.518]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data1.columns

In [34]:
comparison_data

The Call of Cthulhu  ...              Space Odyssey
0    (8.0, 7.73036147548541)  ...   (4.0, 5.161604067162342)
1  (3.0, 3.1665502790306146)  ...   (7.0, 6.368092617608318)
2   (9.0, 8.999705509761078)  ...   (5.0, 7.218260557899971)
3  (nan, 11.020258203343392)  ...    (9.0, 8.82616018736463)
4  (nan, 15.903114781122488)  ...   (7.0, 6.468088534770666)
5  (2.0, 2.2206164938137025)  ...  (nan, 11.452189494325435)
6   (4.0, 4.720681212224078)  ...  (7.0, 4.3123722336478645)
7   (7.0, 6.173912727874322)  ...   (9.0, 7.149291364550851)
8   (3.0, 2.548550319622112)  ...   (3.0, 5.002485836525799)
9    (4.0, 4.81416745151009)  ...   (3.0, 3.517685929710898)

[10 rows x 5 columns]